CostalCloud/force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Certified_Firm__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certified Firm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-boarding</fullName>
                </value>
                <value>
                    <fullName>60 day hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Installer</fullName>
        <active>true</active>
        <label>Installer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Apex_Activation_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings used to disable triggers on demand</description>
    <fields>
        <fullName>Disable_Installers_Available_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all triggers that have been coded to use this custom setting</description>
        <inlineHelpText>Disable all triggers that have been coded to use this custom setting</inlineHelpText>
        <label>Disable Installers Available Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Apex Activation Settings</label>
</CustomObject>

CostalCloud/force-app/main/default/objects/Installers_Available__c.object
<CustomObject>
    <label>Installers Available</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installers Available</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Installer_Account__c.field-meta.xml
<CustomField>
    <fullName>Installer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Installer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assigned Stores</relationshipLabel>
    <relationshipName>Resource_Backup1</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>License Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <label>Store Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only existing Clients can be selected.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installers Available</relationshipLabel>
    <relationshipName>Resource_Backup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Licenses__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certified_Firm__c</fullName>
        <label>Certified Firm</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Certification_State_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Revoke Access</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Liability Insurance</fullName>
                </value>
                <value>
                    <fullName>Business License</fullName>
                </value>
                <value>
                    <fullName>Certified Firm</fullName>
                </value>
                <value>
                    <fullName>Certified Renovator</fullName>
                </value>
                <value>
                    <fullName>City Business License</fullName>
                </value>
                <value>
                    <fullName>City Contractor License</fullName>
                </value>
                <value>
                    <fullName>Client Badge</fullName>
                </value>
                <value>
                    <fullName>County Business License</fullName>
                </value>
                <value>
                    <fullName>County Contractor License</fullName>
                </value>
                <value>
                    <fullName>Electrical License</fullName>
                </value>
                <value>
                    <fullName>General Liability Insurance</fullName>
                </value>
                <value>
                    <fullName>Percentage Agreement</fullName>
                </value>
                <value>
                    <fullName>Plumbing License</fullName>
                </value>
                <value>
                    <fullName>RFI EPA RRP Acknowledgment</fullName>
                </value>
                <value>
                    <fullName>Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Skills Assessment</fullName>
                </value>
                <value>
                    <fullName>State Contractor License</fullName>
                </value>
                <value>
                    <fullName>Workmans Comp Documentation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compliance Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/globalValueSets/Certification_State_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FEDERAL</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>North Carolina</fullName>
    </customValue>
    <customValue>
        <fullName>Oklahoma</fullName>
    </customValue>
    <customValue>
        <fullName>Oklahoma/Federal</fullName>
    </customValue>
    <customValue>
        <fullName>Oregon</fullName>
    </customValue>
    <customValue>
        <fullName>Utah</fullName>
    </customValue>
    <customValue>
        <fullName>Washington</fullName>
    </customValue>
    <customValue>
        <fullName>Washington/Federal</fullName>
    </customValue>
    <customValue>
        <fullName>Wisconsin</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
        <isActive>false</isActive>
        <label>Nebraska</label>
    </customValue>
    <masterLabel>Certification State Values</masterLabel>
</GlobalValueSet>

CostalCloud/force-app/main/default/classes/SG_InstallersAvailableHelper_Test.cls
/***************************************************
* Name:         SG_InstallersAvailableHelper_Test
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         18 May 2021
* ==================================================
* ==================================================
* Purpose:      ...
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       18 May 2021     FMF     Initial Development
* 
****************************************************/

@isTest
public with sharing class SG_InstallersAvailableHelper_Test {
	@TestSetup
	public static void setupData() {

		List<Account> accountList = SG_FSLTestDataSetup.getNewStoreInstallerAccounts();
		insert accountList;
		Account anInstaller = accountList[ 0 ];
		Account aStore = accountList[ 1 ];

		List<Licenses__c> licenseList = new List<Licenses__c>();
		Licenses__c installerLicense = SG_FSLTestDataSetup.getNewLicense(
						SG_FSLTestDataSetup.installerLicenseRTId, anInstaller.Id );
		licenseList.add( installerLicense );

		Licenses__c storeRequiredLicense = SG_FSLTestDataSetup.getNewLicense(
						SG_FSLTestDataSetup.requiredLicenseRTId, aStore.Id );
		licenseList.add( storeRequiredLicense );

		insert licenseList;
	}

	@isTest
	public static void successfullyInsertInstallerAvailableTest() {
		Test.startTest();

		// create/query objects to test
		// installer first, then store
		List<Account> accountList = SG_FSLTestDataSetup.getAccounts();

		Installers_Available__c instAvail =
				SG_FSLTestDataSetup.getNewInstallerAvailable(
						accountList[ 0 ].Id, accountList[ 1 ].Id );

		String error = '';
		try {
			insert instAvail;
		} catch( Exception e ) {
			error = e.getMessage();
		}

		Test.stopTest();

		system.assertEquals( '', error, 'Installer_Available__c record should be inserted with no errors' );
	}

	@isTest
	public static void installerAvailableValidationTest() {
		Test.startTest();

		// create/query objects to test
		// installer first, then store
		List<Account> accountList = SG_FSLTestDataSetup.getAccounts();

		// add required license to store, this is a license that the installer doesn't have
		Licenses__c storeRequiredLicense = SG_FSLTestDataSetup.getNewLicense(
				SG_FSLTestDataSetup.requiredLicenseRTId, accountList[ 1 ].Id );
		storeRequiredLicense.Type__c = 'Certified Firm';
		storeRequiredLicense.Certified_Firm__c = 'FEDERAL';
		insert storeRequiredLicense;

		Installers_Available__c instAvail = new Installers_Available__c();
		instAvail.Installer_Account__c = accountList[ 0 ].Id;
		instAvail.Store_Account__c = accountList[ 1 ].Id;
		instAvail.Status__c = 'Primary';

		String error = '';
		try {
			insert instAvail;
		} catch( Exception e ) {
			error = e.getMessage();
		}

		Test.stopTest();

		system.assertEquals( null, instAvail.Id, 'Installer_Available__c record should NOT be inserted' );
		system.assert( error.containsIgnoreCase( 'Installer doesn\'t have enough active licenses for store' )
				, 'Installer_Available__c insert should result in error' );
	}

	@isTest
	public static void primaryInstallerValidationTest() {
		Test.startTest();

		// create/query objects to test
		// installer first, then store
		List<Account> accountList = SG_FSLTestDataSetup.getAccounts();

		Installers_Available__c instAvail = SG_FSLTestDataSetup.getNewInstallerAvailable(
				accountList[ 0 ].Id, accountList[ 1 ].Id );
		// satisfy validation rule
		instAvail.Percent__c = .5;
		system.debug( 'inserting instAvail= ' + instAvail );
		insert instAvail;

		// second installer expected to fail validation
		Installers_Available__c instAvail2 = instAvail.clone( false );

		String error = '';
		try {
			system.debug( 'inserting instAvail2= ' + instAvail2 );
			insert instAvail2;
		} catch( Exception e ) {
			error = e.getMessage();
		}

		Test.stopTest();

		system.assertEquals( null, instAvail2.Id
					, 'Second primary Installer_Available__c record should NOT be inserted' );
		system.assert( error.containsIgnoreCase( 'already has a primary installer for' )
				, 'Second primary Installer_Available__c insert should result in error' );
	}

	@isTest
	public static void installerAvailableNoLicenseTest() {
		Test.startTest();

		// create/query objects to test
		// installer first, then store
		List<Account> accountList = SG_FSLTestDataSetup.getAccounts();

		// remove licenses from installer
		delete [
				SELECT Id
				FROM Licenses__c
				WHERE Account__c = :accountList[ 0 ].Id
		];

		Installers_Available__c instAvail = SG_FSLTestDataSetup.getNewInstAvailWithoutDependencies(
						accountList[ 0 ].Id, accountList[ 1 ].Id );

		String error = '';
		try {
			insert instAvail;
		} catch( Exception e ) {
			error = e.getMessage();
		}

		Test.stopTest();

		system.assertEquals( null, instAvail.Id, 'Installer_Available__c record should NOT be inserted' );
		system.assert( error.containsIgnoreCase( 'Installer doesn\'t have any required active licenses for store' )
				, 'Installer_Available__c insert should result in error' );
	}

	@IsTest
	public static void testDisabledTrigger() {
		Test.startTest();

		Apex_Activation_Settings__c settings = Apex_Activation_Settings__c.getInstance();
		settings = (Apex_Activation_Settings__c) ( settings == null ? settings : new Apex_Activation_Settings__c() );
		settings.Disable_Installers_Available_Triggers__c = true;
		if( settings.Id != null ) {
			update settings;
		} else {
			insert settings;
		}

		// create/query objects to test
		List<Account> accountList = SG_FSLTestDataSetup.getAccounts();

		Installers_Available__c instAvail = SG_FSLTestDataSetup.getNewInstAvailWithoutDependencies(
				accountList[ 0 ].Id, accountList[ 1 ].Id );
		insert instAvail;

		Test.stopTest();
	}
}