CostalCloud/force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-boarding</fullName>
                </value>
                <value>
                    <fullName>60 day hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Installer</fullName>
        <active>true</active>
        <label>Installer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Installers_Available__c.object
<CustomObject>
    <label>Installers Available</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installers Available</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Installer_Account__c.field-meta.xml
<CustomField>
    <fullName>Installer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Installer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assigned Stores</relationshipLabel>
    <relationshipName>Resource_Backup1</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>xJob Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Measure</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>License Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <label>Store Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only existing Clients can be selected.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installers Available</relationshipLabel>
    <relationshipName>Resource_Backup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Store_Name__c.field-meta.xml
<CustomField>
    <fullName>Store_Name__c</fullName>
    <formula>Store_Account__r.Name</formula>
    <label>Store Name</label>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/SvcTypeCode__c.field-meta.xml
<CustomField>
    <fullName>SvcTypeCode__c</fullName>
    <label>SvcTypeCode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/Licenses__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Matching_Key__c</fullName>
        <formula>TEXT( Type__c )
+ &apos;^&apos; + TEXT( Certified_Firm__c )
+ &apos;^&apos; + TEXT( Certified_Renovator__c )
+ &apos;^&apos; + TEXT( City__c )
+ &apos;^&apos; + TEXT( County__c )

/* no longer match by state 
+ &apos;^&apos; + TEXT( State__c )

*/</formula>
        <label>Matching Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Revoke Access</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Liability Insurance</fullName>
                </value>
                <value>
                    <fullName>Business License</fullName>
                </value>
                <value>
                    <fullName>Certified Firm</fullName>
                </value>
                <value>
                    <fullName>Certified Renovator</fullName>
                </value>
                <value>
                    <fullName>City Business License</fullName>
                </value>
                <value>
                    <fullName>City Contractor License</fullName>
                </value>
                <value>
                    <fullName>Client Badge</fullName>
                </value>
                <value>
                    <fullName>County Business License</fullName>
                </value>
                <value>
                    <fullName>County Contractor License</fullName>
                </value>
                <value>
                    <fullName>Electrical License</fullName>
                </value>
                <value>
                    <fullName>General Liability Insurance</fullName>
                </value>
                <value>
                    <fullName>Percentage Agreement</fullName>
                </value>
                <value>
                    <fullName>Plumbing License</fullName>
                </value>
                <value>
                    <fullName>RFI EPA RRP Acknowledgment</fullName>
                </value>
                <value>
                    <fullName>Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Skills Assessment</fullName>
                </value>
                <value>
                    <fullName>State Contractor License</fullName>
                </value>
                <value>
                    <fullName>Workmans Comp Documentation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>svcTypeCode__c</fullName>
        <label>svcTypeCode</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Compliance Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/classes/SG_InstallersAvailableHelper.cls
/***************************************************
* Name:         SG_InstallersAvailableHelper
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         12 May 2021
* ==================================================
* ==================================================
* Purpose:      ...
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       12 May 2021     FMF     Initial Development
* 
****************************************************/

public with sharing class SG_InstallersAvailableHelper {
	public static Set<ID> recordIdsAlreadyProcessedSet = new Set<ID>();

	public static void validateInstaller( TriggerOperation operationType, List<Installers_Available__c> newList
			, Map<ID, Installers_Available__c> oldMap ) {

		// When an Installer is "assigned" to a client such as Home Depot we need something that compares
		// the required licenses identified on client account to all active licenses on the installer
		// account and only allow the relationship if they have a correct match. Exception is if the installer
		// have more licenses than what the customer require. Suggest by start comparing the total number of
		// active licenses at installer. If installer has 3 and client require 4 then it is already rejected.
		// If the installer has 4 or more and client require 4 then compare data elements between the two.
		//
		// There is an expiration date on the license that the installer has. When the license is expired we
		// need the related list between the client and the installer to reflect that the license has "expired".
		// Installer_Account__c, Job_Type_Category__c, Status__c, Store_Account__c
		//
		// prevent more than one primary installer per category, job type and store

		if( operationType != TriggerOperation.BEFORE_INSERT
				&& operationType != TriggerOperation.BEFORE_UPDATE ) {
			return;
		}

		// collect store and installer Ids
		Set<ID> accountIDset = getAccountIds( newList, oldMap );
		if( accountIDset.isEmpty() ) {
			return;
		}

		// get existing primary installers
		Map<String, Installers_Available__c> primaryInstallerMap = getPrimaryInstallersMap( accountIDset );

		// collect and separate license Ids per parent account
		// Matching_Key__c is a concatenation of fields to match licenses
		List<Licenses__c> licenseList = getStoreLicenseList( accountIDset );
		Map<Id, Set<String>> licensesPerAccountMap = getLicensesPerAccount( licenseList );

		// check installer licenses against store required licenses
		for( Installers_Available__c anInstallerAvailable : newList ) {
			Installers_Available__c oldInstaller = ( oldMap != null ?
							oldMap.get( anInstallerAvailable.Id ) : null );

			// check if there already is a primary installer available
			// when updating:  check if status has been changed to Primary
			if( anInstallerAvailable.Status__c == 'Primary'
					&& ( oldInstaller == null || oldInstaller.Status__c != anInstallerAvailable.Status__c ) ) {
				String theKey = anInstallerAvailable.Store_Account__c
								+ '^' + anInstallerAvailable.Category__c
								+ '^' + anInstallerAvailable.Job_Type__c
								+ '^' + anInstallerAvailable.SvcTypeCode__c;
				system.debug( 'checking key= ' + theKey );
				if( primaryInstallerMap.containsKey( theKey ) ) {
					anInstallerAvailable.addError( 'Store '
							+ anInstallerAvailable.Store_Name__c + ' already has a primary installer for '
							+ anInstallerAvailable.Category__c + ' / ' + anInstallerAvailable.Job_Type__c
							+ ' / svc type code ' + anInstallerAvailable.SvcTypeCode__c );
					continue;
				}
			}

			Set<String> requiredLicenseSet = licensesPerAccountMap.get( anInstallerAvailable.Store_Account__c );
			if( requiredLicenseSet == null ) {
				// store doesn't require any licenses
				continue;
			}

			Set<String> installerLicenseSet = licensesPerAccountMap.get( anInstallerAvailable.Installer_Account__c );
			if( installerLicenseSet == null ) {
				// report installer without licenses
				String missingLicenseList = getMissingLicenseList( requiredLicenseSet, new Set<String>() );
				anInstallerAvailable.addError( 'Installer doesn\'t have any required active licenses for store '
											+ anInstallerAvailable.Store_Name__c + '.'
											+ ' Missing licenses:  ' + missingLicenseList );
				continue;
			}

			if( installerLicenseSet.containsAll( requiredLicenseSet ) ) {
				// installer has all required licenses
				continue;
			}

			// installer is missing licenses
			// identify which licenses are missing
			String missingLicenseList = getMissingLicenseList( requiredLicenseSet, installerLicenseSet );

			anInstallerAvailable.addError( 'Installer doesn\'t have enough active licenses for store '
					+ anInstallerAvailable.Store_Name__c + '.'
					+ ' Missing licenses:  ' + missingLicenseList );
		}
	}

	public static String getMissingLicenseList( Set<String> requiredLicenseSet, Set<String> installerLicenseSet ) {
		Set<String> missingLicenseSet = requiredLicenseSet.clone();
		missingLicenseSet.removeAll( installerLicenseSet );

		String missingLicenseList = '';
		for( String aLicenseMatchingKey : missingLicenseSet ) {
			// type is the first field in the concatenated formula
			String licenseType = aLicenseMatchingKey.substringBefore( '^' );
			//system.debug( 'aLicenseMatchingKey= ' + aLicenseMatchingKey );
			//system.debug( 'licenseType= ' + licenseType );
			missingLicenseList = missingLicenseList + ', ' + licenseType;
		}
		if( missingLicenseList.length() > 2 ) {
			missingLicenseList = missingLicenseList.substring( 2 );
		}
		system.debug( 'missingLicenseList= ' + missingLicenseList );
		return missingLicenseList;
	}

	public static Set<ID> getAccountIds( List<Installers_Available__c> newList
								, Map<ID, Installers_Available__c> oldMap ) {
		Set<ID> accountIDset = new Set<ID>();
		for( Installers_Available__c anInstallerAvailable : newList ) {
			if( recordIdsAlreadyProcessedSet.contains( anInstallerAvailable.ID ) ) {
				continue;
			}
			if( anInstallerAvailable.ID != null ) {
				recordIdsAlreadyProcessedSet.add( anInstallerAvailable.ID );
			}

			// skip if no relevant field has changed
			Installers_Available__c oldInstaller = ( oldMap != null ?
							oldMap.get( anInstallerAvailable.Id ) : null );
			if( oldInstaller != null && oldInstaller.Status__c != anInstallerAvailable.Status__c
					&& oldInstaller.Store_Account__c != anInstallerAvailable.Store_Account__c
					&& oldInstaller.Category__c != anInstallerAvailable.Category__c
					&& oldInstaller.Job_Type__c != anInstallerAvailable.Job_Type__c
					&& oldInstaller.SvcTypeCode__c != anInstallerAvailable.SvcTypeCode__c ) {
				continue;
			}

			// collect account Ids in the same set - will run a single query for both
			accountIDset.add( anInstallerAvailable.Store_Account__c );
			accountIDset.add( anInstallerAvailable.Installer_Account__c );
		}
		system.debug( 'accountIDset= ' + accountIDset );
		return accountIDset;
	}

	public static Map<String, Installers_Available__c> getPrimaryInstallersMap( Set<Id> storeIDset ) {
		List<Installers_Available__c> primaryInstallerList = [
				SELECT Id, Name, Store_Account__c, Category__c, Job_Type__c, SvcTypeCode__c, Percent__c
				FROM Installers_Available__c
				WHERE Store_Account__c IN :storeIDset
					AND Status__c = 'Primary'
		];
		system.debug( 'primaryInstallerList= ' + primaryInstallerList );

		Map<String, Installers_Available__c> primaryInstallerMap = new Map<String, Installers_Available__c>();
		for( Installers_Available__c anInstaller : primaryInstallerList ) {
			String theKey = anInstaller.Store_Account__c
					+ '^' + anInstaller.Category__c + '^' + anInstaller.Job_Type__c
					+ '^' + anInstaller.SvcTypeCode__c;
			primaryInstallerMap.put( theKey, anInstaller );
		}
		system.debug( 'primaryInstallerMap= ' + primaryInstallerMap );

		return primaryInstallerMap;
	}

	public static List<Licenses__c> getStoreLicenseList( Set<Id> storeIDset ) {
		// store required doesn't need status Active
		List<Licenses__c> licenseList = [
				SELECT Id, Name, Account__c, Account__r.Name
						, RecordType.Name, City__c
						, Expiration_Date__c, Type__c, Status__c
						, Matching_Key__c
				FROM Licenses__c
				WHERE Account__c IN :storeIDset
					AND ( RecordType.Name = 'Store Required License'
						OR Status__c = 'Active' )
		];
		// 20210916 - removed , State__c as per Eva
		system.debug( 'licenseList= ' + licenseList );
		return licenseList;
	}

	public static Map<Id, Set<String>> getLicensesPerAccount( List<Licenses__c> licenseList ) {
		Map<Id, Set<String>> licensesPerAccountMap = new Map<Id, Set<String>>();
		for( Licenses__c aLicense : licenseList ) {
			Set<String> licenseMatchingKeySet = licensesPerAccountMap.get( aLicense.Account__c );
			if( licenseMatchingKeySet == null ) {
				licenseMatchingKeySet = new Set<String>();
			}
			licenseMatchingKeySet.add( aLicense.Matching_Key__c );
			licensesPerAccountMap.put( aLicense.Account__c, licenseMatchingKeySet );
		}
		system.debug( 'licensesPerAccountMap= ' + licensesPerAccountMap );
		return licensesPerAccountMap;
	}

}