CostalCloud/force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <formula>IF ( INCLUDES ( Reporting_Market__r.Program__c  , &quot;Core&quot; ), &quot;Core; &quot;,null ) &amp;
IF ( INCLUDES ( Reporting_Market__r.Program__c  , &quot;Kitchens&quot; ), &quot;Kitchens; &quot;,null ) &amp;
IF ( INCLUDES ( Reporting_Market__r.Program__c , &quot;TCS&quot; ), &quot;TCS; &quot;,null )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Before activating an Installer Portal Account make sure that they have their own Service Territory setup and that all resources have been linked to the same territory.</inlineHelpText>
        <label>Service Territory</label>
        <referenceTo>ServiceTerritory</referenceTo>
        <relationshipLabel>Installer Account Record</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Installer</fullName>
        <active>true</active>
        <label>Installer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Installers_Available__c.object
<CustomObject>
    <label>Installers Available</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installers Available</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Installer_Account__c.field-meta.xml
<CustomField>
    <fullName>Installer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Installer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assigned Stores</relationshipLabel>
    <relationshipName>Resource_Backup1</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <label>Store Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only existing Clients can be selected.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installers Available</relationshipLabel>
    <relationshipName>Resource_Backup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/SvcTypeCode__c.field-meta.xml
<CustomField>
    <fullName>SvcTypeCode__c</fullName>
    <label>SvcTypeCode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/Job_SKU__c.object
<CustomObject>
    <label>Job SKU</label>
    <nameField>
        <label>Job SKU #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job SKU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Job_SKU__c/fields/Job_SKU__c.field-meta.xml
<CustomField>
    <fullName>Job_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Unique Job SKU #</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CostalCloud/force-app/main/default/objects/Rules_Regs__c.object
<CustomObject>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HDS</fullName>
                </value>
                <value>
                    <fullName>Murphy Doors</fullName>
                </value>
                <value>
                    <fullName>NIS</fullName>
                </value>
                <value>
                    <fullName>TCS</fullName>
                </value>
                <value>
                    <fullName>THD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Installation_State__c</fullName>
        <label>Installation State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job SKU</label>
        <referenceTo>Job_SKU__c</referenceTo>
        <relationshipLabel>Rules/Regs</relationshipLabel>
        <relationshipName>Rules_Regs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store/Client</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rules/Regs</relationshipLabel>
        <relationshipName>Rules_Regs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rules/Regs</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Rules/Regs #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules/Regs</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>RRP</fullName>
        <active>true</active>
        <label>RRP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/WorkOrder.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <formula>TEXT(  Client_Store__r.Type  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Type</label>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/epaInfo_calcYrBuilt__c.field-meta.xml
<CustomField>
    <fullName>epaInfo_calcYrBuilt__c</fullName>
    <label>Client Calculated Year Home Built</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Home_Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Home_Year_Built__c</fullName>
    <inlineHelpText>Enter full year (4 characters) i/e 1995, not 95</inlineHelpText>
    <label>Year Home Built</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Integration_Key_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key_WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Integration Key (WorkOrder)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Job_SKU__c.field-meta.xml
<CustomField>
    <fullName>Job_SKU__c</fullName>
    <inlineHelpText>If integration cannot find the Job SKU the lookup field will be blank but this field will be populated and business can research and create appropriate Job SKU record.</inlineHelpText>
    <label>Job SKU (text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Job_Type_request_change__c.field-meta.xml
<CustomField>
    <fullName>Job_Type_request_change__c</fullName>
    <label>Job Type request change</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30-Day Tune-Up</fullName>
            </value>
            <value>
                <fullName>Additional Service/Labor</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
            <value>
                <fullName>Trip Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Permit_Attached_Review_Request__c.field-meta.xml
<CustomField>
    <fullName>Permit_Attached_Review_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit Attached Review Request</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Permit_Required_calculated__c.field-meta.xml
<CustomField>
    <fullName>Permit_Required_calculated__c</fullName>
    <inlineHelpText>If client/store (account) has a rules/regs record with matching Program, Category and svcCodeType.  If all of those are matching check the STATE on the Work Order and compare it to the rules/regs object.  If rules/regs object &quot;Installation_State_c&quot; field says &quot;Any&quot; or if it the state code is a direct match to the state on the work order (address field) then the work order is marked for &quot;Permit Required = Yes&quot;.</inlineHelpText>
    <label>Permit Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Primary_Field_Manager__c.field-meta.xml
<CustomField>
    <fullName>Primary_Field_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Based on program</inlineHelpText>
    <label>Primary Field Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/RRP_Required_Calculated__c.field-meta.xml
<CustomField>
    <fullName>RRP_Required_Calculated__c</fullName>
    <label>RRP Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Yes - Year Difference</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/svcTypeCode__c.field-meta.xml
<CustomField>
    <fullName>svcTypeCode__c</fullName>
    <label>svcTypeCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/recordTypes/Installation.recordType-meta.xml
<RecordType>
    <fullName>Installation</fullName>
    <active>true</active>
    <label>Installation</label>
</RecordType>

CostalCloud/force-app/main/default/classes/SG_WorkOrderHelper_Test.cls
/***************************************************
* Name:         SG_WorkOrderHelper_Test
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         03 Jun 2021
* ==================================================
* ==================================================
* Purpose:      ...
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       03 Jun 2021     FMF     Initial Development
* 
****************************************************/

@isTest
public with sharing class SG_WorkOrderHelper_Test {
	@TestSetup
	public static void setupData() {

//		// add approval user to queue
//		addUserToApprovalQueue( 'Work Order RRP Queue' );

		WorkType installWorkType = SG_FSLTestDataSetup.getNewWorkType( 'Installation' );
		WorkType measureWorkType = SG_FSLTestDataSetup.getNewWorkType( 'Measurement' );
		insert new List<WorkType> {
				installWorkType, measureWorkType
		};

		OperatingHours theHours = SG_FSLTestDataSetup.getNewOperatingHours();
		insert theHours;

		ServiceTerritory aSvcTerr = SG_FSLTestDataSetup.getNewServiceTerritory( theHours.ID );
		insert aSvcTerr;

		Pricebook2 aPB = new Pricebook2();
		aPB.Name = '123';
		insert aPB;

		List<Account> accountList = SG_FSLTestDataSetup.getNewStoreInstallerAccounts();
		Account anInstaller = accountList[ 0 ];
		anInstaller.Service_Territory__c = aSvcTerr.Id;

		Account aStore = accountList[ 1 ];
		insert accountList;

		Installers_Available__c instAvail =
				SG_FSLTestDataSetup.getNewInstallerAvailable(
						anInstaller.Id, aStore.Id );
		insert instAvail;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( null, null );

		Account personAccount = SG_WorkOrderHelper.getNewPersonAccount( aWorkOrder );
		insert personAccount;

		aWorkOrder.svcTypeCode__c = 'M';
		aWorkOrder.AccountId = personAccount.Id;
		insert aWorkOrder;

		String orgId = Userinfo.getOrganizationID();
		String uniqueEmail = 'test@' + orgId + '.net.test';
		User anIntegrationUser = new User( Alias = 'TST'
				, CommunityNickname = 'TST'
				, Email = uniqueEmail
				, EmailEncodingKey = 'UTF-8'
				, LastName = 'Integration Testing'
				, LanguageLocaleKey = 'en_US'
				, LocaleSidKey = 'en_US'
				, Profile = new Profile( Name = 'Standard User' )
				, TimezoneSidKey = 'America/Los_Angeles'
				, UserName = uniqueEmail );
		insert anIntegrationUser;
	}

//	public static void addUserToApprovalQueue( String queueName ) {
//		User u = SG_FSLTestDataSetup.getNewUser( 'Manager' );
//		u.ManagerId = UserInfo.getUserId();
//		u.Profile = new Profile( Name = 'System Administrator' );
//		insert u;
//
//		system.runAs( u ) {
//			Group approvalQueue = [
//					SELECT Id
//					FROM Group
//					WHERE Name = :queueName
//					AND Type = 'Queue'
//			];
//			system.debug( 'approvalQueue= ' + approvalQueue );
//
//			GroupMember member = new GroupMember();
//			member.UserOrGroupId = u.Id;
//			member.GroupId = approvalQueue.Id;
//			insert member;
//		}
//	}

	@IsTest
	public static void testBulkWorkOrders() {
		Test.startTest();

		Integer nbrRecords = 140;

		Account store = SG_FSLTestDataSetup.getTestStore();

		Id rrpRTId = ruleRegRtMap.get( 'RRP' ).getRecordTypeId();

		// create matching rules/regulations record
		Rules_Regs__c ruleReg = getNewRuleRegulation( rrpRTId );
		system.debug( 'creating RRP ruleReg= ' + ruleReg );
		insert ruleReg;

		// create/query objects to test
		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		Installers_Available__c instAvail = [
				SELECT Id, Installer_Account__c
				FROM Installers_Available__c
				WHERE Store_Account__c = :store.Id
				LIMIT 1
		];

		List<WorkOrder> workOrderList = new List<WorkOrder>();
		WorkOrder templateWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		for( Integer i = 0; i < nbrRecords; i++ ) {
			WorkOrder aWorkOrder = templateWorkOrder.clone();
			aWorkOrder.Integration_Key_WorkOrder__c = 'TEST' + i;
			workOrderList.add( aWorkOrder );
		}
		insert workOrderList;


		Test.stopTest();
	}

	@IsTest
	public static void approvalProcessTest() {
		Test.startTest();

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.Primary_Field_Manager__c = UserInfo.getUserId();
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		insert aWorkOrder;

		SG_WorkOrderHelper.recordIdsAlreadyCheckedForApprovalSet.clear();
		SG_WorkOrderHelper.integrationKeysAlreadyCheckedForApprovalSet.clear();

		aWorkOrder.Permit_Attached_Review_Request__c = true;
		system.debug( 'updating work order for permit approval process= ' + aWorkOrder );
		update aWorkOrder;

		Test.stopTest();

		List<ProcessInstance> processList =
				SG_WorkOrderHelper.getProcessListForRecordIds( new Set<Id> { aWorkOrder.Id } );

		system.assertEquals( 1, processList.size(), 'workorder must now have an approval process started' );

	}

	@IsTest
	public static void flagPermitRequiredTest() {
		Test.startTest();

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Id permitRTId = ruleRegRtMap.get( 'Permit' ).getRecordTypeId();

		// create matching rules/regulations record
		Rules_Regs__c ruleReg = getNewRuleRegulation( permitRTId );
		ruleReg.Store_Client__c = store.Id;
		system.debug( 'creating Permit ruleReg= ' + ruleReg );
		insert ruleReg;

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.epaInfo_calcYrBuilt__c = '1999';
		aWorkOrder.Home_Year_Built__c = '1999';
		aWorkOrder.Job_Type_request_change__c = null;
		aWorkOrder.StateCode = 'TX';
		aWorkOrder.Integration_Key_WorkOrder__c = 'DEF456';
		system.debug( 'inserting aWorkOrder for permit= ' + aWorkOrder );
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assertEquals( SG_WorkOrderHelper.REQUIRED_RULE_REGULATION_STATE
				, aWorkOrder.Permit_Required_Calculated__c
				, 'Permit flag should be Yes' );

		system.assertEquals( SG_WorkOrderHelper.NOT_REQUIRED_RULE_REGULATION_STATE
				, aWorkOrder.RRP_Required_Calculated__c
				, 'RRP flag should be No since there is no rule/regulation for RRP' );
	}

	@IsTest
	public static void flagRRPRequiredWithDifferentYearsTest() {
		Test.startTest();

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Id rrpRTId = ruleRegRtMap.get( 'RRP' ).getRecordTypeId();

		// create matching rules/regulations record
		Rules_Regs__c ruleReg = getNewRuleRegulation( rrpRTId );
		system.debug( 'creating RRP ruleReg= ' + ruleReg );
		insert ruleReg;

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.epaInfo_calcYrBuilt__c = '1970';
		aWorkOrder.Home_Year_Built__c = '1969';
		aWorkOrder.Job_Type_request_change__c = null;
		aWorkOrder.StateCode = 'TX';
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		system.debug( 'inserting aWorkOrder for permit= ' + aWorkOrder );
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assertEquals( SG_WorkOrderHelper.REQUIRED_RULE_REGULATION_STATE_YEAR_DIFF
					, aWorkOrder.RRP_Required_Calculated__c
				, 'RRP flag should be Yes with year difference noted' );

		system.assertEquals( SG_WorkOrderHelper.NOT_REQUIRED_RULE_REGULATION_STATE
				, aWorkOrder.Permit_Required_Calculated__c
				, 'Permit flag should be No since there is no rule/regulation for Permit' );
	}

	@IsTest
	public static void flagRRPRequiredTest() {
		Test.startTest();

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Id rrpRTId = ruleRegRtMap.get( 'RRP' ).getRecordTypeId();

		// create matching rules/regulations record
		Rules_Regs__c ruleReg = getNewRuleRegulation( rrpRTId );
		ruleReg.Installation_State__c = 'TX';
		system.debug( 'creating RRP ruleReg for TX= ' + ruleReg );
		insert ruleReg;

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.Job_Type_request_change__c = null;
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		system.debug( 'inserting aWorkOrder for permit= ' + aWorkOrder );
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assertEquals( SG_WorkOrderHelper.NOT_REQUIRED_RULE_REGULATION_STATE
				, aWorkOrder.Permit_Required_Calculated__c
				, 'Permit flag should be No since there is no rule/regulation for Permit' );

		system.assertEquals( SG_WorkOrderHelper.REQUIRED_RULE_REGULATION_STATE
				, aWorkOrder.RRP_Required_Calculated__c
				, 'RRP flag should be Yes' );
	}

	public static Map<String, Schema.RecordTypeInfo> ruleRegRtMap = Schema.SObjectType.Rules_Regs__c.getRecordTypeInfosByName();

	public static Rules_Regs__c getNewRuleRegulation( Id permitRTId ) {
		Rules_Regs__c ruleReg = new Rules_Regs__c();
		//ruleReg.Name = '';
		ruleReg.RecordTypeId = permitRTId;
		ruleReg.Client_Type__c = 'THD';
		ruleReg.Program__c = 'Doors';
		ruleReg.Category__c = 'Exterior Door';
		ruleReg.svcCodeType__c = 'I';
		ruleReg.Installation_State__c = 'All';
		system.debug( 'new ruleReg for testing= ' + ruleReg );
		return ruleReg;
	}

	@isTest
	public static void populateLookupTest() {
		Test.startTest();

		Account store = SG_FSLTestDataSetup.getTestStore();

		// create/query objects to test
		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.svcTypeCode__c = 'I';
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		system.debug( 'inserting aWorkOrder= ' + aWorkOrder );
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assertEquals( 'SGI Test Installer', aWorkOrder.Installer__r.Name
				, 'Work order should now have a installer' );
		system.assert( aWorkOrder.ServiceTerritoryId != null
				, 'Work order should now have a service territory' );
		// case 3361 - we no longer want the work type to auto populate on create, remove the above from the code
//		system.assertEquals( 'Installation', aWorkOrder.WorkType.Name
//				, 'Work order should have the correct work type' );
		system.assertEquals( '123', aWorkOrder.Pricebook2.Name
				, 'Work order should have the correct pricebook' );
		system.assert( aWorkOrder.AccountId != null
				, 'Work order should have a person account' );

		// this part only applies to integration users
		system.assertEquals( null, aWorkOrder.ParentWorkOrder.svcTypeCode__c
				, 'Work order should NOT have parent work order for Measurement while changed by non-integration user' );

		// increase coverage
		Set<Id> woIdSet = new Set<Id> { aWorkOrder.Id };
		List<WorkOrderShare> newShareList = [
				SELECT Id, UserOrGroupId, UserOrGroup.Name
				FROM WorkOrderShare
				WHERE ParentId IN :woIdSet
					AND AccessLevel = 'Edit'
					AND RowCause = 'Manual'
		];
		system.assertEquals( 1, newShareList.size()
				, 'Work order shares should have been created for territory' );
		SG_WorkOrderHelper.deleteOldWorkOrderShares( woIdSet );
	}

	@isTest
	public static void populateLookupAsIntegrationUserTest() {
		Test.startTest();

		User integrationUser = [
				SELECT Id
				FROM User
				WHERE LastName = 'Integration Testing'
		];

		Account store = SG_FSLTestDataSetup.getTestStore();

		// create/query objects to test
		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder;
		system.runAs( integrationUser ) {

			Account anotherStore = store.clone( false );
			anotherStore.Name = '2nd Store';
			insert anotherStore;

			aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( anotherStore, sku );
			aWorkOrder.svcTypeCode__c = 'I';
			aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
			system.debug( 'inserting aWorkOrder= ' + aWorkOrder );
			insert aWorkOrder;
		}

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		// this part only applies to integration users
		system.assertEquals( 'M', aWorkOrder.ParentWorkOrder.svcTypeCode__c
				, 'Work order should have parent work order for Measurement while changed by integration user' );
	}

		@isTest
	public static void validateMeasurementInstallerTest() {
		Test.startTest();

		Account store = SG_FSLTestDataSetup.getTestStore();

		// create/query objects to test
		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		Account anInstaller = [
				SELECT Id
				FROM Account
				WHERE Name = 'SGI Test Installer'
		];

		Installers_Available__c instAvail = [
				SELECT Id, Installer_Account__c
				FROM Installers_Available__c
				WHERE Store_Account__c = :store.Id
				LIMIT 1
		];
		instAvail.SvcTypeCode__c = 'M';
		instAvail.Status__c = 'Secondary';
		update instAvail;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.svcTypeCode__c = 'M';
		aWorkOrder.Installer__c = instAvail.Installer_Account__c;
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		system.debug( 'inserting aWorkOrder= ' + aWorkOrder );
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assertEquals( 'SGI Test Installer', aWorkOrder.Installer__r.Name
				, 'Work order should now have a installer' );
	}

	@isTest
	public static void workOrderWithNewAccountTest() {
		Test.startTest();

		Account store = SG_FSLTestDataSetup.getTestStore();

		// create/query objects to test
		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.svcTypeCode__c = 'I';
		aWorkOrder.CustomerFirstName__c = 'Mary';
		aWorkOrder.CustomerLastName__c = 'Lunchbucket';
		aWorkOrder.Integration_Key_WorkOrder__c = 'MaryLunchbucket123';
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assert( aWorkOrder.AccountId != null
				, 'Work order should have a person account' );
//		system.assert( aWorkOrder.ContactId != null
//				, 'Work order should have a person account contact' );

	}

	@isTest
	public static void workOrderWithoutAccountTest() {
		Test.startTest();

		Account store = SG_FSLTestDataSetup.getTestStore();

		// create/query objects to test
		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		// work order without full customer information should not have account assigned
		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.svcTypeCode__c = 'I';
		aWorkOrder.CustomerFirstName__c = '';
		aWorkOrder.CustomerLastName__c = 'Lunchbucket';
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assert( aWorkOrder.AccountId == null
				, 'Work order should NOT have a person account' );
		system.assert( aWorkOrder.ContactId == null
				, 'Work order should NOT have a person account contact' );

	}

	public static WorkOrder getWorkOrder( Id aWorkOrderId ) {
		WorkOrder aWorkOrder = [
				SELECT Id, Installer__c, Installer__r.Name, ServiceTerritoryId
						, WorkType.Name, Pricebook2.Name, AccountId, ContactId
						, ParentWorkOrder.svcTypeCode__c
						, RRP_Required_Calculated__c
						, Permit_Required_Calculated__c
				FROM WorkOrder
				WHERE Id = :aWorkOrderId
		];
		return aWorkOrder;
	}

	@IsTest
	public static void testDisabledTrigger() {
		Test.startTest();

		Apex_Activation_Settings__c settings = Apex_Activation_Settings__c.getInstance();
		settings = (Apex_Activation_Settings__c) ( settings == null ? settings : new Apex_Activation_Settings__c() );
		settings.Disable_WorkOrder_Triggers__c = true;
		if( settings.Id != null ) {
			update settings;
		} else {
			insert settings;
		}

		// create/query objects to test
		WorkOrder aWorkOrder = new WorkOrder();
		insert aWorkOrder;

		aWorkOrder = getWorkOrder( aWorkOrder.Id );

		Test.stopTest();

		system.assert( aWorkOrder.Installer__c == null
				, 'Work order should NOT have a installer' );
	}

	@IsTest
	public static void statusHistoryTrackingTest() {
		Test.startTest();

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.Primary_Field_Manager__c = UserInfo.getUserId();
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		aWorkOrder.Status = 'Open';
		aWorkOrder.Sub_Status__c = 'Pending Initial Contact';
		insert aWorkOrder;

		//SG_WorkOrderHelper.statusChangesAlreadyProcessedSet.clear();
		SG_WorkOrderHelper.recordIdsAlreadySharedSet.clear();
		SG_WorkOrderHelper.integrationKeysAlreadySharedSet.clear();

		aWorkOrder.Status = 'Scheduled';
		aWorkOrder.Sub_Status__c = 'Scheduled';
		system.debug( 'updating work order for status tracking= ' + aWorkOrder );
		update aWorkOrder;

		Test.stopTest();

		List<Work_Order_History__c> statusHistoryList = [
				SELECT Id, Date_Time_of_Change__c
				, Status_Changed_to__c, Sub_Status_Changed_To__c
				FROM Work_Order_History__c
				WHERE Work_Order__c = :aWorkOrder.Id
				ORDER BY Date_Time_of_Change__c
		];

		system.assertEquals( 2, statusHistoryList.size(), 'status history should have 2 records' );
		system.assertEquals( 'Pending Initial Contact', statusHistoryList[ 0 ].Sub_Status_Changed_To__c
				, 'status history should contain PAST sub status' );
		system.assertEquals( 'Scheduled', statusHistoryList[ 1 ].Sub_Status_Changed_To__c
				, 'status history should contain CURRENT sub status' );

	}
}