CostalCloud/force-app/main/default/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Installer</fullName>
        <active>true</active>
        <label>Installer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Apex_Activation_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings used to disable triggers on demand</description>
    <fields>
        <fullName>Disable_SA_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Svc Appointment Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Apex Activation Settings</label>
</CustomObject>

CostalCloud/force-app/main/default/objects/Job_SKU__c.object
<CustomObject>
    <label>Job SKU</label>
    <nameField>
        <label>Job SKU #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job SKU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Job_SKU__c/fields/Job_SKU__c.field-meta.xml
<CustomField>
    <fullName>Job_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Unique Job SKU #</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CostalCloud/force-app/main/default/objects/TCS_Resource_Cross_Reference__c.object
<CustomObject>
    <description>Table to hold TCS contacts that will also be used for service resource lookup to accounts etc.</description>
    <label>TCS Resource Cross Reference</label>
    <nameField>
        <label>TCS Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TCS Resource Cross Reference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/TCS_Resource_Cross_Reference__c/fields/Installer_Account__c.field-meta.xml
<CustomField>
    <fullName>Installer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TCS Resource Cross Reference</relationshipLabel>
    <relationshipName>TCS_Resource_Cross_Reference</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/TCS_Resource_Cross_Reference__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <inlineHelpText>Will be auto populated based on the &quot;Name&quot; field.  Only one resource per unique full name allowed.</inlineHelpText>
    <label>Unique Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Installer__c.field-meta.xml
<CustomField>
    <fullName>Installer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Company</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only accounts with record type of &quot;Installer&quot; may be selected.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Installer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Installer_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Integration_Key_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key_WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Integration Key (WorkOrder)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Job_SKU__c.field-meta.xml
<CustomField>
    <fullName>Job_SKU__c</fullName>
    <inlineHelpText>If integration cannot find the Job SKU the lookup field will be blank but this field will be populated and business can research and create appropriate Job SKU record.</inlineHelpText>
    <label>Job SKU (text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Primary_Field_Manager__c.field-meta.xml
<CustomField>
    <fullName>Primary_Field_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Based on program</inlineHelpText>
    <label>Primary Field Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Initial Contact</fullName>
                <default>true</default>
                <label>Pending Initial Contact</label>
            </value>
            <value>
                <fullName>Pending Customer Response</fullName>
            </value>
            <value>
                <fullName>Pending Customer Contact</fullName>
            </value>
            <value>
                <fullName>Need Store Assistance</fullName>
            </value>
            <value>
                <fullName>Need FM/RM Assistance</fullName>
            </value>
            <value>
                <fullName>Customer Not Ready</fullName>
            </value>
            <value>
                <fullName>Pending Product</fullName>
            </value>
            <value>
                <fullName>Pending Document Review</fullName>
            </value>
            <value>
                <fullName>Pending Permit</fullName>
            </value>
            <value>
                <fullName>Unscheduled</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Missing Documents</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
            <value>
                <fullName>Client Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Updated PO</fullName>
            </value>
            <value>
                <fullName>Pending Installer Pay</fullName>
            </value>
            <value>
                <fullName>Pending Payment Confirmation</fullName>
            </value>
            <value>
                <fullName>Exported to Client</fullName>
            </value>
            <value>
                <fullName>Processed Installer Pay</fullName>
            </value>
            <value>
                <fullName>Pending KeyRec</fullName>
            </value>
            <value>
                <fullName>Pending Client Payment</fullName>
            </value>
            <value>
                <fullName>Pending Payment Resolution</fullName>
            </value>
            <value>
                <fullName>Chargeback in Process</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Confirm PO Assistance</fullName>
            </value>
            <value>
                <fullName>Confirm PO Assistance Complete</fullName>
            </value>
            <value>
                <fullName>Accounting Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/classes/SG_SAHelper_Test.cls
/***************************************************
* Name:         SG_SAHelper_Test
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         09 Sep 2021
* ==================================================
* ==================================================
* Purpose:      ...
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       09 Sep 2021     FMF     Initial Development
*
****************************************************/

@IsTest
public with sharing class SG_SAHelper_Test {
	@TestSetup
	public static void setupData() {
		List<Account> accountList = SG_FSLTestDataSetup.getNewStoreInstallerAccounts();
		insert accountList;
	}

	@IsTest
	public static void testWorkOrderDates() {

		Test.startTest();

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.Primary_Field_Manager__c = UserInfo.getUserId();
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		insert aWorkOrder;

		ServiceAppointment svcAppt = SG_FSLTestDataSetup.getNewServiceAppointment( aWorkOrder );
		svcAppt.Status = SG_SAHeper.APPT_STATUS_DISPATCHED;
		svcAppt.SchedStartTime = Datetime.now().addDays( 12 );
		svcAppt.SchedEndTime = Datetime.now().addDays( 14 );
		insert svcAppt;

		Test.stopTest();

		aWorkOrder = [
				SELECT Id, StartDate, EndDate, Sub_Status__c
				FROM WorkOrder
				WHERE Id = :aWorkOrder.Id
		];

		system.assertEquals( svcAppt.SchedStartTime.date(), aWorkOrder.StartDate.date()
										, 'WO start date must match svc appt' );
		system.assertEquals( svcAppt.SchedEndTime.date(), aWorkOrder.EndDate.date()
										, 'WO end date must match svc appt' );
		system.assertEquals( SG_SAHeper.WO_SUBSTATUS_SCHEDULED, aWorkOrder.Sub_Status__c
										, 'WO sub status must be Scheduled' );
	}

	@IsTest
	public static void testResetWorkOrderDates() {

		Test.startTest();

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.Primary_Field_Manager__c = UserInfo.getUserId();
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		insert aWorkOrder;

		ServiceAppointment svcAppt = SG_FSLTestDataSetup.getNewServiceAppointment( aWorkOrder );
		svcAppt.Status = SG_SAHeper.APPT_STATUS_CANCELED;
		svcAppt.SchedStartTime = Datetime.now().addDays( 2 );
		svcAppt.SchedEndTime = Datetime.now().addDays( 4 );
		insert svcAppt;

		Test.stopTest();

		aWorkOrder = [
				SELECT Id, StartDate, EndDate, Sub_Status__c
				FROM WorkOrder
				WHERE Id = :aWorkOrder.Id
		];

		system.assertEquals( null, aWorkOrder.StartDate, 'WO start date must be null' );
		system.assertEquals( null, aWorkOrder.EndDate, 'WO end date must be null' );
		system.assertEquals( SG_SAHeper.WO_SUBSTATUS_CANCELED, aWorkOrder.Sub_Status__c
				, 'WO sub status must be Canceled' );
	}

	@IsTest
	public static void testDisabledTrigger() {
		Test.startTest();

		Apex_Activation_Settings__c settings = Apex_Activation_Settings__c.getInstance();
		settings = (Apex_Activation_Settings__c) ( settings == null ? settings : new Apex_Activation_Settings__c() );
		settings.Disable_SA_Triggers__c = true;
		if( settings.Id != null ) {
			update settings;
		} else {
			insert settings;
		}

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		insert aWorkOrder;

		ServiceAppointment svcAppt = SG_FSLTestDataSetup.getNewServiceAppointment( aWorkOrder );
		svcAppt.Status = SG_SAHeper.APPT_STATUS_CANCELED;
		svcAppt.SchedStartTime = Datetime.now().addDays( 2 );
		svcAppt.SchedEndTime = Datetime.now().addDays( 4 );
		insert svcAppt;

		Test.stopTest();
	}

	@IsTest
	public static void testXrefMatch() {

		// create/query objects to test
		Account store = SG_FSLTestDataSetup.getTestStore();
		Account installer = SG_FSLTestDataSetup.getNewStoreInstallerAccounts()[0];

		Job_SKU__c sku = SG_FSLTestDataSetup.getNewSku();
		insert sku;

		WorkOrder aWorkOrder = SG_FSLTestDataSetup.getNewWorkOrder( store, sku );
		aWorkOrder.Primary_Field_Manager__c = UserInfo.getUserId();
		aWorkOrder.Integration_Key_WorkOrder__c = 'ABC123';
		insert aWorkOrder;

		ServiceAppointment svcAppt = SG_FSLTestDataSetup.getNewServiceAppointment( aWorkOrder );
		svcAppt.Status = SG_SAHeper.APPT_STATUS_CANCELED;
		svcAppt.SchedStartTime = Datetime.now().addDays( 2 );
		svcAppt.SchedEndTime = Datetime.now().addDays( 4 );
		insert svcAppt;


		TCS_Resource_Cross_Reference__c xref = new TCS_Resource_Cross_Reference__c();
		String unique = 'Xref XYZ zdf__ ' + String.valueOf( Crypto.getRandomInteger() );
		xref.Name = unique;
		xref.Unique_Name__c = unique;
		xref.Installer_Account__c = installer.Id;
		insert xref;

		svcAppt = [SELECT Id, Installer__c FROM ServiceAppointment WHERE Id = :svcAppt.Id LIMIT 1];
		System.assertEquals(null, svcAppt.Installer__c );

		Test.startTest();
		SG_SAHeper.hasMatchedInstaller = false;
		svcAppt.TCS_Assigned_Resource__c = unique;
		update svcAppt;
		Test.stopTest();

		svcAppt = [SELECT Id, Installer__c FROM ServiceAppointment WHERE Id = :svcAppt.Id LIMIT 1];
		System.assertEquals( svcAppt.Installer__c, installer.Id );
	}


}