CostalCloud/force-app/main/default/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Installer</fullName>
        <active>true</active>
        <label>Installer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/PO_Notes__c.object
<CustomObject>
    <label>PO Notes</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PO Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/PO_Notes__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>PO Notes</relationshipLabel>
    <relationshipName>PO_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Installer_Action__c.field-meta.xml
<CustomField>
    <fullName>Installer_Action__c</fullName>
    <label>Installer Action</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Not Responding</fullName>
            </value>
            <value>
                <fullName>Customer Requested Call Back</fullName>
            </value>
            <value>
                <fullName>Customer Requested Cancelation</fullName>
            </value>
            <value>
                <fullName>Emergency/Health</fullName>
            </value>
            <value>
                <fullName>FM/RM Updated</fullName>
            </value>
            <value>
                <fullName>Left Message</fullName>
            </value>
            <value>
                <fullName>Need Address Verification - Invalid Address</fullName>
            </value>
            <value>
                <fullName>Need Valid Contact Information</fullName>
            </value>
            <value>
                <fullName>PO Assigned to Wrong Installer</fullName>
            </value>
            <value>
                <fullName>PO Incorrect/Update Required</fullName>
            </value>
            <value>
                <fullName>Product Damaged/Defective</fullName>
            </value>
            <value>
                <fullName>Product Delayed</fullName>
            </value>
            <value>
                <fullName>Product Incorrect</fullName>
            </value>
            <value>
                <fullName>Product Not Available</fullName>
            </value>
            <value>
                <fullName>Product Received</fullName>
            </value>
            <value>
                <fullName>Questions/Concerns on PO</fullName>
            </value>
            <value>
                <fullName>Store Updated</fullName>
            </value>
            <value>
                <fullName>Waiting on Design/Product Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/PO_Note_AutoCreated__c.field-meta.xml
<CustomField>
    <fullName>PO_Note_AutoCreated__c</fullName>
    <description>Via trigger, if this field is populated, it will create PO Note for Work Order and then clear out this field.</description>
    <label>PO Note</label>
    <type>TextArea</type>
</CustomField>

CostalCloud/force-app/main/default/classes/SG_PONotesHelper_Test.cls
/***************************************************
* Name:         SG_PONotesHelper_Test
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         Nov 2021
* ==================================================
* ==================================================
* Purpose:      Test methods for SG_PHNOtesHelper
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       Nov 2021        GO          Initial Development
*
****************************************************/
@IsTest
private class SG_PONotesHelper_Test
{

    static testMethod void testBehavior()
    {
        SG_TestDataGenerator td = new SG_TestDataGenerator();
        Account a = td.getAccounts(false)[0];
        insert a;

        // create workorder
        WorkOrder wo = new WorkOrder();
        wo.AccountId = a.Id;
        wo.Status = 'Open';
        insert wo;

        SG_PONotesHelper.processPONOtes_Ran = false;
        // update work order Installer Action
        wo.Installer_Action__c = 'Left Message';
        wo.PO_Note_Autocreated__c = 'Test Message12345678900000000000000000000000000000000000000000000000000000000000555';

        Test.startTest();
        update wo;
        Test.stopTest();

        // confirm PO Note created
        List<PO_Notes__c> notes = [SELECT Id, Name, Work_Order__c FROM PO_Notes__c WHERE Name LIKE 'Test Message%'];
        System.assert(notes.size() == 1);
        System.assertEquals(wo.Id, notes[0].Work_Order__c);
    }
}