CostalCloud/force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Market</label>
        <referenceTo>Client_Market__c</referenceTo>
        <relationshipLabel>Client Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-boarding</fullName>
                </value>
                <value>
                    <fullName>60 day hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Installer</fullName>
        <active>true</active>
        <label>Installer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Client_Market__c.object
<CustomObject>
    <label>Client Market</label>
    <nameField>
        <label>Client Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Client_Market__c/fields/Market_Number__c.field-meta.xml
<CustomField>
    <fullName>Market_Number__c</fullName>
    <label>Client Market Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c.object
<CustomObject>
    <label>Installers Available</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installers Available</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>License Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/Installers_Available__c/fields/SvcTypeCode__c.field-meta.xml
<CustomField>
    <fullName>SvcTypeCode__c</fullName>
    <label>SvcTypeCode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/Job_SKU__c.object
<CustomObject>
    <label>Job SKU</label>
    <nameField>
        <label>Job SKU #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job SKU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Job_SKU__c/fields/Job_SKU__c.field-meta.xml
<CustomField>
    <fullName>Job_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Unique Job SKU #</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CostalCloud/force-app/main/default/objects/Licenses__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Liability Insurance</fullName>
                </value>
                <value>
                    <fullName>Business License</fullName>
                </value>
                <value>
                    <fullName>Certified Firm</fullName>
                </value>
                <value>
                    <fullName>Certified Renovator</fullName>
                </value>
                <value>
                    <fullName>City Business License</fullName>
                </value>
                <value>
                    <fullName>City Contractor License</fullName>
                </value>
                <value>
                    <fullName>Client Badge</fullName>
                </value>
                <value>
                    <fullName>County Business License</fullName>
                </value>
                <value>
                    <fullName>County Contractor License</fullName>
                </value>
                <value>
                    <fullName>Electrical License</fullName>
                </value>
                <value>
                    <fullName>General Liability Insurance</fullName>
                </value>
                <value>
                    <fullName>Percentage Agreement</fullName>
                </value>
                <value>
                    <fullName>Plumbing License</fullName>
                </value>
                <value>
                    <fullName>RFI EPA RRP Acknowledgment</fullName>
                </value>
                <value>
                    <fullName>Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Skills Assessment</fullName>
                </value>
                <value>
                    <fullName>State Contractor License</fullName>
                </value>
                <value>
                    <fullName>Workmans Comp Documentation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>svcTypeCode__c</fullName>
        <label>svcTypeCode</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Compliance Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/WorkOrder.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Client_Market__c.field-meta.xml
<CustomField>
    <fullName>Client_Market__c</fullName>
    <formula>Client_Store__r.Client_Market__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Market</label>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Client_Store__c.field-meta.xml
<CustomField>
    <fullName>Client_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client/Store</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only accounts with type of Client or Internal may be selected.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Client/Store)</relationshipLabel>
    <relationshipName>Client_Store_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/CustomerEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerEmail__c</fullName>
    <label>CustomerEmail</label>
    <type>Email</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/CustomerFirstName__c.field-meta.xml
<CustomField>
    <fullName>CustomerFirstName__c</fullName>
    <inlineHelpText>Populated from integration</inlineHelpText>
    <label>CustomerFirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/CustomerLastName__c.field-meta.xml
<CustomField>
    <fullName>CustomerLastName__c</fullName>
    <inlineHelpText>Populated from integration</inlineHelpText>
    <label>CustomerLastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/CustomerPhone__c.field-meta.xml
<CustomField>
    <fullName>CustomerPhone__c</fullName>
    <inlineHelpText>Comes from integration</inlineHelpText>
    <label>Customer Mobile Phone</label>
    <type>Phone</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/epaInfo_calcYrBuilt__c.field-meta.xml
<CustomField>
    <fullName>epaInfo_calcYrBuilt__c</fullName>
    <label>Client Calculated Year Home Built</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Home_Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Home_Year_Built__c</fullName>
    <inlineHelpText>Enter full year (4 characters) i/e 1995, not 95</inlineHelpText>
    <label>Year Home Built</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Integration_Key_WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key_WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Integration Key (WorkOrder)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Job_SKU__c.field-meta.xml
<CustomField>
    <fullName>Job_SKU__c</fullName>
    <inlineHelpText>If integration cannot find the Job SKU the lookup field will be blank but this field will be populated and business can research and create appropriate Job SKU record.</inlineHelpText>
    <label>Job SKU (text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Job_SKU_lookup__c.field-meta.xml
<CustomField>
    <fullName>Job_SKU_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job SKU</label>
    <referenceTo>Job_SKU__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/svcTypeCode__c.field-meta.xml
<CustomField>
    <fullName>svcTypeCode__c</fullName>
    <label>svcTypeCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Measure</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Site Verification</fullName>
            </value>
            <value>
                <fullName>Product Check-In</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Trip Charge</fullName>
            </value>
            <value>
                <fullName>Additional Service/Labor</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
            <value>
                <fullName>30-Day Tune-Up</fullName>
            </value>
            <value>
                <fullName>Escalated Customer</fullName>
            </value>
            <value>
                <fullName>CB-Canceled Not Replaced</fullName>
            </value>
            <value>
                <fullName>CB-Canceled Replaced</fullName>
            </value>
            <value>
                <fullName>CB-External</fullName>
            </value>
            <value>
                <fullName>CB-Reduced PO</fullName>
            </value>
            <value>
                <fullName>CB-Installer to Installer</fullName>
            </value>
            <value>
                <fullName>CB-Badge Charge</fullName>
            </value>
            <value>
                <fullName>CB-Clothing</fullName>
            </value>
            <value>
                <fullName>CB-Child Support</fullName>
            </value>
            <value>
                <fullName>CB-Loans/Installer Payment Plans</fullName>
            </value>
            <value>
                <fullName>CB-Tax Liens</fullName>
            </value>
            <value>
                <fullName>CB-Badge Violation</fullName>
            </value>
            <value>
                <fullName>CB-RRP Fine (External)</fullName>
            </value>
            <value>
                <fullName>CB-RRP Fine (Internal)</fullName>
            </value>
            <value>
                <fullName>CB-Sponsorships</fullName>
            </value>
            <value>
                <fullName>MP-Market to Installer</fullName>
            </value>
            <value>
                <fullName>MP-Installer to Installer</fullName>
            </value>
            <value>
                <fullName>MP-Sponsorships</fullName>
            </value>
            <value>
                <fullName>Legal Tender Matter</fullName>
            </value>
            <value>
                <fullName>Property Damage Claim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/classes/SG_FSLTestDataSetup.cls
/***************************************************
* Name:         SG_FSLTestDataSetup
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         03 Jun 2021
* ==================================================
* ==================================================
* Purpose:      ...
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       03 Jun 2021     FMF     Initial Development
* 
****************************************************/
@IsTest
public with sharing class SG_FSLTestDataSetup {
    private static final String DOORS_PROGRAM = 'Doors';
    private static final String STORE_NAME = 'SGI THD Store Test';

    public static Id requiredLicenseRTId = Schema.SObjectType.Licenses__c.getRecordTypeInfosByName().get( 'Store Required License' ).getRecordTypeId();
    public static Id installerLicenseRTId = Schema.SObjectType.Licenses__c.getRecordTypeInfosByName().get( 'Installer License' ).getRecordTypeId();
    public static Id installerRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get( 'Installer' ).getRecordTypeId();
    public static Id storeRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get( 'Client' ).getRecordTypeId();

    public static WorkOrder getNewWorkOrder( Account store, Job_SKU__c sku ) {
        WorkOrder aWorkOrder = new WorkOrder();
        aWorkOrder.Client_Store__c = ( store != null ? store.Id : null );
        aWorkOrder.Job_SKU_lookup__c = ( sku != null ? sku.Id : null );
        aWorkOrder.CustomerFirstName__c = 'Joe';
        aWorkOrder.CustomerLastName__c = 'Sixpack';
        aWorkOrder.CustomerPhone__c = '2142142144';
        aWorkOrder.CustomerEmail__c = 'joeSixpack@mailinator.com';
        aWorkOrder.SvcTypeCode__c = 'I';
        aWorkOrder.epaInfo_calcYrBuilt__c = '1960';
        aWorkOrder.Home_Year_Built__c = '1960';
        aWorkOrder.StateCode = 'TX';
        aWorkOrder.Integration_Key_WorkOrder__c = 'JoeSixpackTest';
        system.debug( 'new WorkOrder for testing= ' + aWorkOrder );
        return aWorkOrder;
    }

    public static List<Account> getNewStoreInstallerAccounts() {
        List<Account> accountList = new List<Account>();
        Account anInstaller = new Account();
        anInstaller.Name = 'SGI Test Installer';
        anInstaller.RecordTypeId = installerRTId;
        anInstaller.BillingStateCode = 'TX';
        accountList.add( anInstaller );

        Client_Market__c aMarket = new Client_Market__c();
        aMarket.Market_Number__c = 123;
        insert aMarket;

        Account aStore = new Account();
        aStore.Name = STORE_NAME;
        aStore.RecordTypeId = storeRTId;
        aStore.Client_Market__c = aMarket.Id;
        aStore.BillingStateCode = 'TX';
        aStore.Type = 'THD';
        accountList.add( aStore );

        return accountList;
    }

    public static Account getTestStore() {
        Account store = [
                SELECT Id
                FROM Account
                WHERE Name = :STORE_NAME
        ];
        system.debug( 'got store for testing= ' + store );
        return store;
    }

    public static Licenses__c getNewLicense( Id aRecordTypeId, Id parentAccountId ) {
        Licenses__c installerLicense = new Licenses__c();
        installerLicense.RecordTypeId = aRecordTypeId;
        installerLicense.Account__c = parentAccountId;
        installerLicense.Type__c = 'City';
        installerLicense.City__c = 'Contractor';
        installerLicense.Status__c = 'Active';
        return installerLicense;
    }

    public static Installers_Available__c getNewInstAvailWithoutDependencies(
            Id installerId, Id storeId ) {
        Installers_Available__c instAvail = new Installers_Available__c();
        instAvail.Installer_Account__c = installerId;
        instAvail.Store_Account__c = storeId;
        instAvail.Status__c = 'Primary';
        return instAvail;
    }

    public static final String EXTERIOR_DOOR = 'Exterior Door';

    public static Installers_Available__c getNewInstallerAvailable(
            Id installerId, Id storeId ) {
        Installers_Available__c instAvail = getNewInstAvailWithoutDependencies( installerId, storeId );
        instAvail.Job_Type__c = 'Install';

        // if any of the dependencies below change, it will break
        instAvail.Client__c = 'THD';
        instAvail.Program__c = DOORS_PROGRAM;
        instAvail.Category__c = EXTERIOR_DOOR;
        instAvail.SvcTypeCode__c = 'I';

        return instAvail;
    }

    public static Job_SKU__c getNewSku() {
        Job_SKU__c sku = new Job_SKU__c();
        sku.Category__c = EXTERIOR_DOOR;
        sku.Program__c = DOORS_PROGRAM;
        system.debug( 'new sku for testing= ' + sku );
        return sku;
    }

    public static List<Account> getAccounts() {
        List<Account> accountList = [
                SELECT Id, Name
                FROM Account
                ORDER BY CreatedDate
        ];
        return accountList;
    }

    public static OperatingHours getNewOperatingHours() {
        OperatingHours theHours = new OperatingHours();
        theHours.Name = 'Sixpack hours';
        theHours.TimeZone = 'America/Chicago';
        return theHours;
    }

    public static ServiceTerritory getNewServiceTerritory( Id operHoursId ) {
        ServiceTerritory resourcesTerritory = new ServiceTerritory();
        resourcesTerritory.Name = 'Sixpack TEST territory';
        resourcesTerritory.OperatingHoursId = operHoursId;
        resourcesTerritory.IsActive = true;
        return resourcesTerritory;
    }

    public static ServiceAppointment getNewServiceAppointment( WorkOrder aWorkOrder ) {
        ServiceAppointment svcAppt = new ServiceAppointment();
        svcAppt.ParentRecordId = aWorkOrder.Id;
        return svcAppt;
    }

    public static WorkType getNewWorkType( String aName ) {
        WorkType aWorkType = new WorkType();
        aWorkType.Name = aName;
        aWorkType.EstimatedDuration = 1;
        return aWorkType;
    }

    public static Contact getNewContact( String lastName ) {
        Contact workOrderContact = new Contact();
        workOrderContact.FirstName = 'Joe';
        workOrderContact.LastName = lastName;
        workOrderContact.Phone = '2142142144';
        workOrderContact.Email = 'joe' + lastName + '@mailinator.com';
        workOrderContact.MailingStreet = '123 Main';
        workOrderContact.MailingCity = 'Somewhere';
        return workOrderContact;
    }

    public static User getNewUser( String aName ) {
        String orgId = Userinfo.getOrganizationID();
        String uniqueEmail = 'test' + aName + '@' + orgId + '.net.test';
        User anUser = new User( Alias = 'TST'
                , CommunityNickname = uniqueEmail.remove( '@' )
                , Email = uniqueEmail
                , EmailEncodingKey = 'UTF-8'
                , FirstName = 'Joe'
                , LastName = aName + ' TEST'
                , LanguageLocaleKey = 'en_US'
                , LocaleSidKey = 'en_US'
                // TODO:  change this profile name
                , Profile = new Profile( Name = '#Custom: RFI Standard' )
                , TimezoneSidKey = 'America/Los_Angeles'
                , UserName = uniqueEmail );
        return anUser;
    }

    public static Schema.Location getNewLocation( String name ) {
        Schema.Location territoryLocation = new Schema.Location();
        //territoryLocation.RecordTypeId = ( name.containsIgnoreCase( 'van' ) ? vanRTId : siteRTId );
        territoryLocation.Name = name;
        //territoryLocation.IsInventoryLocation = false;
        territoryLocation.IsInventoryLocation = true;
        territoryLocation.IsMobile = true;
        return territoryLocation;
    }

    public static Schema.Location getLocationWithAddress( String name ) {
        Schema.Location territoryLocation = getNewLocation( name );
        insert territoryLocation;

        Schema.Address aTerritoryAddress = new Schema.Address();
        aTerritoryAddress.ParentId = territoryLocation.Id;
        aTerritoryAddress.PostalCode = '30070';
        //aTerritoryAddress.LocationType = ( name.containsIgnoreCase( 'van' ) ? 'Van' : 'Site' );
        insert aTerritoryAddress;

        return territoryLocation;
    }

    public static ServiceResource getNewServiceResource( User anUser, Id resourceLocationId ) {
        ServiceResource aResource = new ServiceResource();
        aResource.Name = anUser.FirstName + ' ' + anUser.LastName + ', the resource';
        aResource.RelatedRecordId = anUser.Id;
        aResource.LocationId = resourceLocationId;
        aResource.IsActive = true;
        return aResource;
    }

    public static Product2 getNewProduct( Integer nbr ) {
        Product2 p = new Product2();
        p.IsActive = true;
        p.Name = 'Test Product #' + nbr;
        p.ProductCode = 'TestPCode #1' + nbr;
        insert p;

        // create pricebookentries
        PricebookEntry pbe = new PricebookEntry();
        pbe.Product2Id = p.Id;
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.UnitPrice = 1;
        insert pbe;

        return p;
    }

}