CostalCloud/force-app/main/default/objects/Attachment_Files__c.object
<CustomObject>
    <description>Custom Object to allow files to be uploaded with custom fields for Type etc.</description>
    <label>Attachment/Files</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Attachment/Files Auto #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment/Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/Attachment_Files__c/fields/Has_File__c.field-meta.xml
<CustomField>
    <fullName>Has_File__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Trigger populates this field when file is uploaded to the record.</inlineHelpText>
    <label>Has File</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/Attachment_Files__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Changed PO</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>MP/CB Approval</fullName>
            </value>
            <value>
                <fullName>MP/CB Request</fullName>
            </value>
            <value>
                <fullName>Checklist</fullName>
            </value>
            <value>
                <fullName>DDR</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>I2G</fullName>
            </value>
            <value>
                <fullName>ICA</fullName>
            </value>
            <value>
                <fullName>KPW (Labor Bid)</fullName>
            </value>
            <value>
                <fullName>LTE</fullName>
            </value>
            <value>
                <fullName>LTE Proof</fullName>
            </value>
            <value>
                <fullName>LTR</fullName>
            </value>
            <value>
                <fullName>Measure</fullName>
            </value>
            <value>
                <fullName>Permit</fullName>
            </value>
            <value>
                <fullName>Permit Waiver</fullName>
            </value>
            <value>
                <fullName>Pre-Ren</fullName>
            </value>
            <value>
                <fullName>Reduced PO</fullName>
            </value>
            <value>
                <fullName>Service Report</fullName>
            </value>
            <value>
                <fullName>State RRP Form - Alabama</fullName>
            </value>
            <value>
                <fullName>State RRP Form - Mississippi</fullName>
            </value>
            <value>
                <fullName>State RRP Form - Rhode Island</fullName>
            </value>
            <value>
                <fullName>State RRP Form - Wash DC</fullName>
            </value>
            <value>
                <fullName>Wind Storm</fullName>
            </value>
            <value>
                <fullName>Photo</fullName>
            </value>
            <value>
                <fullName>State RRP Form - MS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/classes/SG_FileHelper.cls
/***************************************************
* Name:         SG_FileHelper
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         Nov 2021
* ==================================================
* ==================================================
* Purpose:      ...
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       Nov 2021        GO          Initial Development
*
****************************************************/
public with sharing class SG_FileHelper
{
    public static Boolean processFile_Ran = false;

    public static void processFile(TriggerOperation operation, List<ContentDocumentLink> links)
    {
        System.debug(LoggingLevel.WARN, '==> START SG_FileHelper.processFile()');

        if(operation != TriggerOperation.AFTER_INSERT)
        {
            System.debug(LoggingLevel.WARN, '==> ABORT: operation != TriggerOperation.AFTER_INSERT');
            return;
        }

        if(processFile_Ran == true)
        {
            System.debug(LoggingLevel.WARN, '==> ABORT: processFile_Ran == true');
            return;
        }

        processFile_Ran = true;

        // These are Ids of records File Attachment is associated to
        Set<Id> recordIds = new Set<Id>();
        for(ContentDocumentLink l:links)
        {
            recordIds.add(l.LinkedEntityId);
        }

        // Get Attachment/File Records
        List<Attachment_Files__c> attachmentFiles = [SELECT Id, Type__c FROM Attachment_Files__c WHERE Id IN :recordIds];

        // nothing to process, so return
        if(attachmentFiles.isEmpty()) return;

        for(Attachment_Files__c af:attachmentFiles)
        {
            af.Has_File__c = true;
        }

        update attachmentFiles;

    }

}