CostalCloud/force-app/main/default/objects/PO_Notes__c.object
<CustomObject>
    <label>PO Notes</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PO Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/PO_Notes__c/fields/Auto_Push__c.field-meta.xml
<CustomField>
    <fullName>Auto_Push__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field determines when note is created if it should be auto pushed to client system through API</inlineHelpText>
    <label>Auto Push</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/PO_Notes__c/fields/Private_Note__c.field-meta.xml
<CustomField>
    <fullName>Private_Note__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked auto pushed cannot be send THD and visibility limited to RFI employees and Installer Company</inlineHelpText>
    <label>Private Note?</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/PO_Notes__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>PO Notes</relationshipLabel>
    <relationshipName>PO_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Auto_Push_Note_AutoCreate__c.field-meta.xml
<CustomField>
    <fullName>Auto_Push_Note_AutoCreate__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>When checked, the PO Note will be sent to the Client system</inlineHelpText>
    <label>Auto Push Note</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Do_PO_Note_Validation__c.field-meta.xml
<CustomField>
    <fullName>Do_PO_Note_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, PO Note Validation Rule will run</inlineHelpText>
    <label>Do PO Note Validation</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Installer_Action__c.field-meta.xml
<CustomField>
    <fullName>Installer_Action__c</fullName>
    <label>Installer Action</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Not Responding</fullName>
            </value>
            <value>
                <fullName>Customer Requested Call Back</fullName>
            </value>
            <value>
                <fullName>Customer Requested Cancelation</fullName>
            </value>
            <value>
                <fullName>Emergency/Health</fullName>
            </value>
            <value>
                <fullName>FM/RM Updated</fullName>
            </value>
            <value>
                <fullName>Left Message</fullName>
            </value>
            <value>
                <fullName>Need Address Verification - Invalid Address</fullName>
            </value>
            <value>
                <fullName>Need Valid Contact Information</fullName>
            </value>
            <value>
                <fullName>PO Assigned to Wrong Installer</fullName>
            </value>
            <value>
                <fullName>PO Incorrect/Update Required</fullName>
            </value>
            <value>
                <fullName>Product Damaged/Defective</fullName>
            </value>
            <value>
                <fullName>Product Delayed</fullName>
            </value>
            <value>
                <fullName>Product Incorrect</fullName>
            </value>
            <value>
                <fullName>Product Not Available</fullName>
            </value>
            <value>
                <fullName>Product Received</fullName>
            </value>
            <value>
                <fullName>Questions/Concerns on PO</fullName>
            </value>
            <value>
                <fullName>Store Updated</fullName>
            </value>
            <value>
                <fullName>Waiting on Design/Product Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/PO_Note_Auto_Generated__c.field-meta.xml
<CustomField>
    <fullName>PO_Note_Auto_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Note Auto Generated</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/PO_Note_AutoCreated__c.field-meta.xml
<CustomField>
    <fullName>PO_Note_AutoCreated__c</fullName>
    <description>Via trigger, if this field is populated, it will create PO Note for Work Order and then clear out this field.</description>
    <label>PO Note</label>
    <type>TextArea</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/PO_Note_Subject_AutoCreate__c.field-meta.xml
<CustomField>
    <fullName>PO_Note_Subject_AutoCreate__c</fullName>
    <label>PO Note Subject</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Private_Note_AutoCreate__c.field-meta.xml
<CustomField>
    <fullName>Private_Note_AutoCreate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private Note?</label>
    <type>Checkbox</type>
</CustomField>

CostalCloud/force-app/main/default/objects/WorkOrder/fields/Unscheduled_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unscheduled_Reason__c</fullName>
    <label>Unscheduled Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product Delayed</fullName>
            </value>
            <value>
                <fullName>Product Damaged/Defective</fullName>
            </value>
            <value>
                <fullName>Product Incorrect</fullName>
            </value>
            <value>
                <fullName>Customer Requested New Date</fullName>
            </value>
            <value>
                <fullName>Out of Stock</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Emergency/Health</fullName>
            </value>
            <value>
                <fullName>Customer Requested Cancellation</fullName>
            </value>
            <value>
                <fullName>Scheduled In Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CostalCloud/force-app/main/default/classes/SG_PONotesHelper.cls
/***************************************************
* Name:         SG_PONotesHelper
* Author:       Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date:         Nov 2021
* ==================================================
* ==================================================
* Purpose:      Auto create PO Notes when WorkOrder.PO_Note_AutoCreated__c
*               is populated
*
* ==================================================
* ==================================================
* History:
* VERSION   DATE            INITIALS    DESCRIPTION/FEATURES ADDED
* 1.0       Nov 2021        GO          Initial Development
*
****************************************************/

public with sharing class SG_PONotesHelper
{

    public static Boolean processPONOtes_Ran = false;

    public static void processPONOtes(TriggerOperation operationType, List<WorkOrder> workOrders)
    {
        System.debug(LoggingLevel.WARN, '==> SG_processPONotes()');

        if(operationType != TriggerOperation.BEFORE_UPDATE)
        {
            System.debug(LoggingLevel.WARN, '==> ABORT: operationType != TriggerOperation.BEFORE_UPDATE');
            return;
        }

        if(System.isFuture() || System.isQueueable())
        {
            // do not run this code if it's @future or @queueable
            System.debug(LoggingLevel.WARN, '==> ABORT: System.isFuture() || System.isQueueable()');
            return;
        }

        if(processPONOtes_Ran == true)
        {
            System.debug(LoggingLevel.WARN, '==> ABORT: processPONOtes_Ran == true');
            return;
        }

        processPONOtes_Ran = true;

        // Get Installer Manual Note Record Type
        Id manualRTId;
        try
        {
            manualRTId = Schema.SObjectType.PO_Notes__c.getRecordTypeInfosByName().get('Installer Manual Note').getRecordTypeId();
        }
        catch(Exception e)
        {
            System.debug('Invalid Record Type: Installer Manual Note');
        }

        Id autoRTId;
        try
        {
            autoRTId = Schema.SObjectType.PO_Notes__c.getRecordTypeInfosByName().get('Auto Generated Note').getRecordTypeId();
        }
        catch(Exception e)
        {
            System.debug('Invalid Record Type: Auto Generated Note');
        }

        List<PO_Notes__c> poNotesToCreate = new List<PO_Notes__c>();
        for(WorkOrder wo:workOrders)
        {
            if(wo.PO_Note_AutoCreated__c != null)
            {
                String theNote = wo.PO_Note_AutoCreated__c;

                PO_Notes__c poNote = new PO_Notes__c();
                if(wo.PO_Note_Auto_Generated__c == true)
                {
                    if(autoRTId != null) poNote.RecordTypeId = autoRTId;
                }
                else
                {
                    if(manualRTId != null) poNote.RecordTypeId = manualRTId;
                }

                poNote.Work_Order__c = wo.Id;
                poNote.Name = wo.Installer_Action__c;  // SUBJECT
                if(poNote.Name == null)
                {
                    if(wo.Unscheduled_Reason__c != null)
                    {
                        poNote.Name = wo.Unscheduled_Reason__c;
                    }
                    else
                    {
                        poNote.Name = wo.PO_Note_Subject_AutoCreate__c;
                    }
                }


                poNote.Description__c = theNote;
                if(theNote.length() > 80)
                {
                    poNote.Name = theNote.mid(0, 80);
                }
                poNote.Private_Note__c = wo.Private_Note_AutoCreate__c;
                poNote.Auto_Push__c = wo.Auto_Push_Note_AutoCreate__c;

                poNotesToCreate.add(poNote);
            }
        }

        System.debug(LoggingLevel.WARN, '==>poNOtesToCreate: ' + poNotesToCreate);

        // nothing to process so return
        if(poNotesToCreate.isEmpty()) return;

        try
        {
            System.debug(LoggingLevel.WARN, '==>inserting poNOtesToCreate');
            String poNotes_JSON = JSON.serialize(poNotesToCreate);
            createPONotes(poNotes_JSON);
        }
        catch (Exception e)
        {
            System.debug(LoggingLevel.WARN, '==>inserting poNOtesToCreate ERROR' + e.getStackTraceString() + '; ' + e.getMessage());
        }


    }

    @Future
    public static void createPONotes(String poNotes_JSON)
    {
        // create the manual note
        List<PO_Notes__c> poNotes = (List<PO_Notes__c>)JSON.deserialize(poNotes_JSON, List<PO_Notes__c>.class);
        insert poNotes;

        Set<Id> workOrderIds = new Set<Id>();
        for(PO_Notes__c p:poNotes)
        {
            workOrderIds.add(p.Work_Order__c);
        }

        // reset note fields on the work order record
        List<WorkOrder> workOrders = [SELECT Id FROM WorkOrder WHERE Id IN :workOrderIds];
        for(WorkOrder wo:workOrders)
        {
            wo.Do_PO_Note_Validation__c = false;
            wo.PO_Note_AutoCreated__c = null;
            wo.Private_Note_AutoCreate__c = false;
            wo.Auto_Push_Note_AutoCreate__c = true;
            wo.PO_Note_Subject_AutoCreate__c = null;
            wo.PO_Note_Auto_Generated__c = false;
        }
        update workOrders;
    }

}